name: release

on:
  push:
    tags:  [ "v*" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set GitHub user
        run: |
          git config --global user.name 'oat9002'
          git config --global user.email 'oat9002@hotmail.com'
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Create package
        run: sbt "universal:packageBin"
      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/universal/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
