name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set GitHub user
        run: |
            git config --global user.name 'oat9002'
            git config --global user.email 'oat9002@hotmail.com'
      - name: Release
        run: ./gradlew release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  githubRelease:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set GitHub user
        run: |
          git config --global user.name 'oat9002'
          git config --global user.email 'oat9002@hotmail.com'
      - name: Get latest tag
        run: |
          git pull
          echo ::set-output name=LATEST_TAG::$(git describe --tags --abbrev=0)
        id: get-latest-tag
      - name: Checkout to latest tag
        run: git checkout tags/${{ steps.get-latest-tag.outputs.LATEST_TAG }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Create package
        run: ./gradlew distZip
      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distributions/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
